name: Build
on:
  push:
    branches:
      - main
      - 'axt_**_release_branch'
  pull_request:
    branches:
      - main
      - 'axt_**_release_branch'
env:
  cache-version: v1
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: 'Cache Bazel files'
        uses: actions/cache@v4
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-version }}-bazel-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-version }}-bazel-build-
      - name: Build maven artifacts
        run: bazelisk build //:axt_m2repository
        shell: bash
      - name: cp to upload dir
        run: |
          mkdir -p ~/download
          cp bazel-bin/axt_m2repository.zip ~/download
        shell: bash
      - name: 'Upload local snapshot for tests'
        uses: actions/upload-artifact@v4
        with:
          name: local-snapshot
          path: ~/download
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: 'Cache Bazel files'
        uses: actions/cache@v4
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-version }}-bazel-test-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-version }}-bazel-test-
      - name: Run Robolectric tests and fast tagged tests
        run: bazelisk test --test_tag_filters=robolectric,fast --build_tag_filters=robolectric,fast --test_output=all ...
        shell: bash
